config/routes.rb
Rails.application.routes.draw do
  resources :rides
  resources :available_rides, only: [:index, :create]
  devise_for :drivers
  devise_for :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rides

  def active_ride
    rides.where(status: :pending).last
  end
end

app/models/driver.rb
class Driver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rides

  def active_ride
    rides.where(status: :in_progress).last
  end
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :customer
  belongs_to :driver, optional: true
  enum status: [:pending, :in_progress, :completed, :cancelled]
  delegate :email, to: :customer, prefix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/available_rides_controller.rb
class AvailableRidesController < ApplicationController
  def index
    @available_rides = Ride.pending
  end

  def create
    @ride = Ride.pending.find(params[:ride_id])
    @ride.update(driver_id: current_driver.id, status: :in_progress)
    redirect_to root_path, notice: "You have accepted the ride successfully!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: %i[ show edit update destroy ]

  # GET /rides or /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1 or /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides or /rides.json
  def create
    @ride = current_customer.rides.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to ride_url(@ride), notice: "Ride was successfully created." }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1 or /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to ride_url(@ride), notice: "Ride was successfully updated." }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1 or /rides/1.json
  def destroy
    @ride.destroy!

    respond_to do |format|
      format.html { redirect_to rides_url, notice: "Ride was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ride_params
      params.require(:ride).permit(:pickup_location, :dropoff_location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/available_rides_helper.rb
module AvailableRidesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/available_rides/_available_ride.html.erb
<div class="w-full p-2 bg-gray-300">
  <p class="text-lg"> Ride from <%= ride.pickup_location %> to <%= ride.dropoff_location %> </p>
  <p class="text-lg"> For customer <%= ride.customer_email %> </p>
  <%= link_to "Accept this ride", available_rides_path(ride_id: ride.id), class: "bg-blue-500 p-2 rounded-lg text-lg text-blue-100", 
      data: { turbo_method: :post } %>
</div>

app/views/available_rides/index.html.erb
<div class="flex flex-col items-center pt-16">
  <h1 class="font-bold text-4xl">Viewing all pending Rides </h1>
  <div class="grid gap-4 mt-8">
    <% @available_rides.each do |ride| %>
      <%= render "available_ride", ride: ride %>
    <% end %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruber</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="w-full min-h-[100vh] bg-indigo-500 flex flex-col items-center pt-36">
  <h1 class="font-bold text-6xl">Ruber</h1>
  <p class="text-lg mt-2">A ride sharing app built with Ruby on Rails and Hotwire</p>

  <% if current_customer || current_driver %>
    <% if current_customer %>
      <% if current_customer.active_ride %>
        <p class="text-2xl"> Your ride to <%= current_customer.active_ride.dropoff_location %> is scheduled </p>
      <% else %>
        <%= link_to "Request New Ride", new_ride_path, class: "bg-blue-500 text-blue-50 p-2 rounded-lg" %>
      <% end %>
    <% else %>
      <% if current_driver.active_ride %>
        <p class="text-2xl"> Your driving <%= current_driver.active_ride.customer_email %> to <%= current_driver.active_ride.dropoff_location %> </p>
      <% else %>
        <%= link_to "View Available Rides", available_rides_path, class: "bg-blue-500 text-blue-50 p-2 rounded-lg" %>
      <% end %>
    <% end %>
  <% else %>
    <div class="flex items-center gap-4 mt-6">
      <%= link_to "Sign up as Customer", new_customer_registration_path, class: "bg-blue-500 text-lg p-2 rounded-lg text-gray-100" %>
      <%= link_to "Sign up as Driver", new_driver_registration_path, class: "bg-green-500 text-lg p-2 rounded-lg text-gray-100" %>
    </div>
  <% end %>
</div>

app/views/rides/_form.html.erb
<%= form_with(model: ride, class: "contents") do |form| %>
  <% if ride.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
        <% ride.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :pickup_location %>
    <%= form.text_field :pickup_location, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :dropoff_location %>
    <%= form.text_field :dropoff_location, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/rides/_ride.html.erb
<div id="<%= dom_id ride %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Pickup location:</strong>
    <%= ride.pickup_location %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Dropoff location:</strong>
    <%= ride.dropoff_location %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Customer:</strong>
    <%= ride.customer_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= ride.status %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this ride", ride, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this ride", edit_ride_path(ride), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/rides/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ride</h1>

  <%= render "form", ride: @ride %>

  <%= link_to "Show this ride", @ride, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to rides", rides_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/rides/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Rides</h1>
    <%= link_to "New ride", new_ride_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="rides" class="min-w-full">
    <%= render @rides %>
  </div>
</div>

app/views/rides/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ride</h1>

  <%= render "form", ride: @ride %>

  <%= link_to "Back to rides", rides_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/rides/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ride %>

    <%= link_to "Edit this ride", edit_ride_path(@ride), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this ride", ride_path(@ride), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to rides", rides_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>